export interface UserType {
  addEvents: Boolean,
  approveFiles: Boolean,
  editOthersFiles: Boolean,
  editEvents: Boolean,
  contactExecs: Boolean,
  viewOrganizations: Boolean,
  editOrganizations: Boolean,
  searchPosts: Boolean,
  createPosts: Boolean,
  viewPrivateFiles: Boolean,
  viewEvents: Boolean,
  approveAccounts: Boolean,
  editOwnFiles: Boolean,
  deleteOthersPosts: Boolean,
  createAccounts: Boolean,
  postPublicFiles: Boolean,
  searchFiles: Boolean,
  viewPublicFiles: Boolean,
  deleteOwnPosts: Boolean,
  postPrivateFiles: Boolean,
}
